title: MY AWSOME SITE
author: Tompap2007
email: Tompap2007@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just an awesome description of my awesome site.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
